spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.241.254:3306/nongda?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: hshrpm
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.orhonit.admin.server.sys.model
  mapper-locations: classpath*:/mybatis-mappers/*
files:
  path: ${file-path:d:/files}
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-server.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400
server:
  port: 8080