spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 111111
mybatis:
  type-aliases-package: com.orhonit.admin.server.sys.model
  mapper-locations: classpath*:/mybatis-mappers/*
files:
  path: ${file-path:d:/files}
logging:
  level:
    root: info
    com.zw: debug
 videoconnect:
  path: https://192.168.31.26/m/